// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Suave")>]
[<assembly: AssemblyDescriptionAttribute("Suave — a smooth, open source, F# web server.")>]
[<assembly: AssemblyVersionAttribute("2.5.6")>]
[<assembly: AssemblyFileVersionAttribute("2.5.6")>]
[<assembly: AssemblyMetadataAttribute("Commit","00399c")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Suave"
    let [<Literal>] AssemblyDescription = "Suave — a smooth, open source, F# web server."
    let [<Literal>] AssemblyVersion = "2.5.6"
    let [<Literal>] AssemblyFileVersion = "2.5.6"
    let [<Literal>] AssemblyMetadata_Commit = "00399c"
